config/routes.rb
Rails.application.routes.draw do
  root 'results#index'

  resources :results do
    member do
      get 'download_requests_data'
      get 'download_performance_data'
      get 'report'
    end
  end

  resources :project

  resources :performance_groups do
    resources :performance_labels
  end

  post 'result/performance_plot' => 'results#performance_plot'
  post 'result/requests_seconds_to_values_plot' => 'results#requests_seconds_to_values_plot'
  post 'result/requests_histogram_plot' => 'results#requests_histogram_plot'
  post 'result/all_requests_histogram_plot' => 'results#all_requests_histogram_plot'
  post 'result/percentile_requests_plot' => 'results#percentile_requests_plot'

  namespace :api do
    resources :results, only: [:create, :index]
    resources :results_with_data_id, only: [:create]
  end

  get 'compare' => 'compare#show'
  namespace 'compare' do
    post 'requests_histogram_plot'
    post 'requests_seconds_to_values_plot'
    post 'all_requests_histogram_plot'
    post 'percentile_requests_plot'
    post 'performance_plot'
  end

  get 'trend' => 'trend#show'
  namespace 'trend' do
    post 'requests_plot'
    post 'performance_plot'
    post 'all_requests_stats_plot'
  end

  get '/request_file/:id', to: 'request_file#show'
  post '/request_file', to: 'request_file#create'

  get '/performance_file/:id', to: 'performance_file#show'
  post '/performance_file', to: 'performance_file#create'

end

app/models/result.rb
require 'csv'

class Result < ActiveRecord::Base
  has_many :performance_results, dependent: :delete_all
  has_many :requests_results, dependent: :delete_all
  has_many :calculated_requests_results, dependent: :delete_all
  has_many :calculated_performance_results, dependent: :delete_all
  belongs_to :project

  validates :project_id, presence: true
  validates :version, presence: true
  validates :duration, presence: true
  validates :rps, presence: true
  validates :profile, presence: true
  validate :test_run_date_is_datetime
  validate :release_date_is_date_or_blank

  mount_uploader :requests_data, ResultUploader
  mount_uploader :performance_data, ResultUploader

  filterrific(
      default_filter_params: {sorted_by: 'test_run_date_desc'},
      available_filters: [
          :sorted_by,
          :version_search_query,
          :with_project_id,
          :release_date_gte,
          :release_date_lt,
          :test_run_date_gte,
          :test_run_date_lt
      ]
  )

  scope :version_search_query, lambda {|query|
    return if query.blank?
    terms = query.to_s.downcase.split(/\s+/)
    terms = terms.map {|e|
      ('%' + e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    where(
        terms.map {|term|
          "(LOWER(results.version) LIKE ? )"
        }.join(' AND '),
        *terms.map {|e| [e]}.flatten
    )
  }

  scope :sorted_by, lambda {|sort_option|
    if sort_option =~ /desc$/
      direction = 'desc'
      nulls_pos = 'LAST'
    else
      direction = 'asc'
      nulls_pos = 'FIRST'
    end
    case sort_option.to_s
      when /^test_run_date_/
        order("results.test_run_date #{ direction }")
      when /^version_/
        order("LOWER(results.version) #{ direction }")
      when /^release_date_/
        order("results.release_date #{ direction } NULLS #{nulls_pos}")
      when /^id_/
        order("results.id #{ direction }")
      when /^project_/
        joins(:project).order("projects.project_name #{ direction }, results.project_id #{ direction }")
      when /^rps_/
        order("results.rps #{ direction }")
      when /^duration_/
        order("results.duration #{ direction }")
      when /^profile_/
        order("LOWER(results.profile) #{ direction }")
      when /^data_version_/
        order("case when results.data_version IS NULL or results.data_version = '' THEN 1
                    ELSE 2
                    end #{ direction }, results.data_version #{ direction } ")
      when /^time_cutting_percent_/
        order("results.time_cutting_percent #{ direction }")
      when /^smoothing_percent_/
        order("results.smoothing_percent #{ direction }")
      when /^comment_/
        order("case when results.comment IS NULL or results.comment = '' THEN 1
                    ELSE 2
                    end #{ direction }, results.comment #{ direction } ")
      else
        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  scope :with_project_id, lambda {|project_id|
    where(projects: {id: project_id}).joins(:project)
  }

  scope :release_date_gte, lambda {|reference_time|
    where('results.release_date >= ?', DateTime.parse(reference_time))
  }

  scope :release_date_lt, lambda {|reference_time|
    where('results.release_date < ?', DateTime.parse(reference_time))
  }

  scope :test_run_date_gte, lambda {|reference_time|
    where('results.test_run_date >= ?', DateTime.parse(reference_time))
  }

  scope :test_run_date_lt, lambda {|reference_time|
    where('results.test_run_date < ?', DateTime.parse(reference_time))
  }

  def self.sort_by_version(results)
    results.sort do |a, b|
      a_version = Gem::Version.correct?(normalize_version(a.version)) ? Gem::Version.new(normalize_version(a.version)) : Gem::Version.new(0)
      b_version = Gem::Version.correct?(normalize_version(b.version)) ? Gem::Version.new(normalize_version(b.version)) : Gem::Version.new(0)
      b_version <=> a_version
    end
  end

  def self.normalize_version(version)
    version.gsub(/[^\d,\.]/, '')
  end

  def test_run_date_is_datetime
    errors.add(:test_run_date, 'must be in a datetime format') if test_run_date.nil?
  end

  def release_date_is_date_or_blank
    if read_attribute_before_type_cast('release_date').present?
      errors.add(:release_date, 'must be a valid datetime') if ((DateTime.parse(release_date.to_s) rescue ArgumentError) == ArgumentError)
    end
  end

  def self.upload_and_create(params)
    result = Result.new(
        project_id: params['project'],
        version: params['version'],
        duration: params['duration'],
        rps: params['rps'],
        profile: params['profile'],
        data_version: params['data_version'],
        test_run_date: params['test_run_date'],
        requests_data: params['requests_data'].is_a?(Hash) ? file_from_json(params, 'requests_data') : params['requests_data'],
        performance_data: params['performance_data'].is_a?(Hash) ? file_from_json(params, 'performance_data') : params['performance_data'],
        time_cutting_percent: params['time_cutting_percent'].blank? ? 0 : params['time_cutting_percent'],
        smoothing_percent: params['smoothing_percent'].blank? ? 0 : params['smoothing_percent'],
        release_date: params['release_date']
    )
    result.save

    if result.requests_data.present?
      result.destroy unless save_request_data(result)
    else
      result.destroy
      result.errors.add(:base, 'Request data is required')
    end

    if result.performance_data.present?
      result.destroy unless save_performance_data(result)
    end

    unless result.errors.any?
      calc_request_data(result)
      calc_performance_data(result) unless result.performance_results.empty?
      if params['keep_files'].eql?('not_keep')
        result.remove_requests_data!
        result.remove_performance_data!
        result.save
      end
    end

    result
  end

  def self.update_and_recalculate(result, params)
    previous_time_cut_percent = result.time_cutting_percent
    previous_smooth_percent = result.smoothing_percent
    result.update(
        project_id: params[:project],
        version: params[:version],
        rps: params[:rps],
        duration: params[:duration],
        profile: params[:profile],
        data_version: params[:data_version],
        test_run_date: params[:test_run_date],
        time_cutting_percent: params[:time_cutting_percent].blank? ? 0 : params[:time_cutting_percent],
        smoothing_percent: params[:smoothing_percent].blank? ? 0 : params[:smoothing_percent],
        comment: params[:comment],
        requests_data: params[:requests_data],
        performance_data: params[:performance_data],
        release_date: params[:release_date]
    )

    update_requests(result, params[:requests_data], previous_time_cut_percent, previous_smooth_percent)
    update_performance(result, params[:performance_data], previous_time_cut_percent, previous_smooth_percent)

    result
  end

  def self.border_timestamps(id, table, cut_percent)
    results = table.where(result_id: id)
    min_timestamp = results.minimum(:timestamp)
    max_timestamp = results.maximum(:timestamp)
    cut_timestamp(min_timestamp, max_timestamp, cut_percent)
  end

  def self.cut_timestamp(min, max, cut_percent)
    cut_percent = cut_percent.to_f / 100
    cutted_time = (max - min) * cut_percent
    [(min + cutted_time.to_i), (max - cutted_time.to_i)]
  end

  def self.where_conditional(id = nil, label = nil, bottom_timestamp = nil, top_timestamp = nil)
    where_request = []
    where_request.push "result_id = #{id}" if id
    where_request.push "label = '#{label}'" if label
    where_request.push "timestamp >= #{bottom_timestamp}" if bottom_timestamp
    where_request.push "timestamp <= #{top_timestamp}" if top_timestamp
    where_request.size > 1 ? where_request.join(' AND ') : where_request.join
  end

  def self.values_of_requests(result_id, label = nil, cut_percent)
    where_conditional = where_conditional(result_id, label)
    max_min_timestamps = RequestsResult.max_min_timestamps(where_conditional)
    if cut_percent != 0
      timestamp_min, timestamp_max = cut_timestamp(max_min_timestamps[:min], max_min_timestamps[:max], cut_percent)
      where_conditional = "#{where_conditional} and timestamp >= #{timestamp_min} and timestamp <= #{timestamp_max}"
    end
    RequestsResult.where(where_conditional).pluck(:value)
  end

  def self.percentile_of_values_of_requests(result_id, cut_percent, label = nil)
    values = values_of_requests(result_id, label, cut_percent)
    result = {}
    result[:percentiles] = (0...100).step(10).to_a.push(95).push(99).sort
    result[:values] = result[:percentiles].map {|i| Statistics.percentile(values, i)}
    result
  end

  def self.requests_seconds_to_values(result_id, label, cut_percent)
    result = Result.find_by(id: result_id)
    data = {seconds: [], values: []}

    records = RequestsResult.where(where_conditional(result_id, label)).order(:timestamp).to_a
    timestamp_min, timestamp_max = cut_timestamp(records.first.timestamp, records.last.timestamp, cut_percent)
    records = records.select {|record| record.timestamp >= timestamp_min && record.timestamp <= timestamp_max}
    data[:seconds] = records.map {|record| (record.timestamp - timestamp_min) / 1000}

    values = records.map {|record| record.value}
    data[:values] = if result.smoothing_percent.to_i != 0
                      interval = Statistics.sma_interval(values, result.smoothing_percent)
                      Statistics.simple_moving_average(values, interval)
                    else
                      values
                    end
    data
  end

  def self.performance_seconds_to_values(result_id, labels, cut_percent)
    data = {}
    labels.each do |label|
      data[label] = {seconds: [], values: []}
      bottom_timestamp, top_timestamp = border_timestamps(result_id, PerformanceResult, cut_percent)

app/controllers/api/results_controller.rb
class Api::ResultsController < ApiController
  def create
    params['project'] = Project.find_by(project_name: params['project']).try(:id)
    params['keep_files'] = 'keep' if params['keep_files'].nil?
    result = Result.upload_and_create(params)

    if result.errors.empty?
      render json: {result_id: result.id, status: 'created'}
    else
      render json: result.errors.full_messages, :status => :bad_request
    end
  end

  def index
    results = Result.all
    results = ResultFilter.new(results, params).filter
    render json: results.as_json(except: %i[requests_data performance_data])
  end



end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy, :download_requests_data, :download_performance_data, :report]

  def index
    @filterrific = initialize_filterrific(
        Result,
        params[:filterrific],
        select_options: {
            with_project_id: Project.options_for_select
        }
    ) or return
    @results = @filterrific.find.page(params[:page])

  rescue ActiveRecord::RecordNotFound => e
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return

  end

  def show
  end

  def new
  end

  def edit
    flash.now[:version] = @result[:version]
    flash.now[:rps] = @result[:rps]
    flash.now[:duration] = @result[:duration]
    flash.now[:profile] = @result[:profile]
    flash.now[:data_version] = @result[:data_version]
    flash.now[:test_run_date] = @result[:test_run_date].try(:strftime, '%d.%m.%Y %H:%M')
    flash.now[:time_cutting_percent] = @result[:time_cutting_percent]
    flash.now[:smoothing_percent] = @result[:smoothing_percent]
    flash.now[:release_date] = @result[:release_date].try(:strftime, '%d.%m.%Y %H:%M')
    flash.now[:comment] = @result[:comment]
    flash.now[:requests_data_identifier] = @result.requests_data_identifier
    flash.now[:performance_data_identifier] = @result.performance_data_identifier
  end

  def update
    result = Result.update_and_recalculate(@result, params)
    if result.errors.empty?
      redirect_to(results_url, notice: 'Result was successfully updated.')
    else
      flash.now[:version] = params[:version]
      flash.now[:rps] = params[:rps]
      flash.now[:duration] = params[:duration]
      flash.now[:profile] = params[:profile]
      flash.now[:data_version] = params[:data_version]
      flash.now[:test_run_date] = params[:test_run_date]
      flash.now[:time_cutting_percent] = params[:time_cutting_percent]
      flash.now[:smoothing_percent] = params[:smoothing_percent]
      flash.now[:release_date] = params[:release_date]
      flash.now[:comment] = params[:comment]
      flash.now[:requests_data_identifier] = @result.requests_data_identifier
      flash.now[:performance_data_identifier] = @result.performance_data_identifier
      flash.now[:alert] = result.errors.full_messages
      render action: :edit
    end
  end

  def create
    params['keep_files'] = 'not_keep' unless params['keep_files']
    result = Result.upload_and_create(params)
    if result.errors.empty?
      redirect_to(results_url, notice: 'Result was successfully created.')
    else
      flash.now[:version] = params[:version]
      flash.now[:rps] = params[:rps]
      flash.now[:duration] = params[:duration]
      flash.now[:profile] = params[:profile]
      flash.now[:data_version] = params[:data_version]
      flash.now[:test_run_date] = params[:test_run_date]
      flash.now[:time_cutting_percent] = params[:time_cutting_percent]
      flash.now[:smoothing_percent] = params[:smoothing_percent]
      flash.now[:release_date] = params[:release_date]
      flash.now[:alert] = result.errors.full_messages
      render action: :new
    end
  end

  def destroy
    @result.destroy
    redirect_to results_url, notice: 'Result was successfully destroyed.'
  end

  def download_requests_data
    send_file @result.requests_data.current_path
  end

  def download_performance_data
    send_file @result.performance_data.current_path
  end

  def report
  end

  def performance_plot
    group = params[:group]
    @unit = group[:units]
    @group_name = group[:name]
    @plot_id = params[:plot_id]
    @result_data = Result.performance_seconds_to_values(params[:result_id], group[:labels], params[:result_time_cut].to_i)
  end

  def requests_histogram_plot
    @plot_id = params[:plot_id]
    @result_data = Result.values_of_requests(params[:result_id], params[:label], params[:result_time_cut].to_i)
  end

  def requests_seconds_to_values_plot
    @plot_id = params[:plot_id]
    @result_data = Result.requests_seconds_to_values(params[:result_id], params[:label], params[:result_time_cut].to_i)
  end

  def all_requests_histogram_plot
    @result_data = Result.values_of_requests(params[:result_id], params[:result_time_cut].to_i)
  end

  def percentile_requests_plot
    @plot_id = params[:plot_id]
    @result_data = Result.percentile_of_values_of_requests(params[:result_id], params[:result_time_cut].to_i, params[:label])
  end

  private

  def set_result
    @result = Result.find_by(id: params[:id])
  end
end

app/helpers/results_helper.rb
module ResultsHelper
  def comment_icon(comment)
    "<i class=\"glyphicon glyphicon-envelope data-toggle=\"tooltip\" title=\"#{comment}\"></i>".html_safe
  end
end

app/views/results/_performance_data_report.html.erb
<div class="panel-group" id="perfmon_data">
  <div class="panel panel-default">
    <div class="panel-heading">

      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#perfmon_data" href="#collapsePerfmonData">
          Performance results
        </a>
      </h4>

    </div>
    <div id="collapsePerfmonData" class="panel-collapse collapse in">
      <div class="panel-body">
        <% @result.performance_groups.each do |group| %>
            <% case %>
        <% when group[:metrics_type] == PerformanceGroup.define_metrics_type[:dynamic], group[:metrics_type] == nil %>
                <%= render(
                        partial: 'results/performance_dynamic_metrics_report',
                        locals: {group: group}
                    ) %>
            <% when group[:metrics_type] == PerformanceGroup.define_metrics_type[:static] %>
                <%= render(
                        partial: 'results/performance_static_metrics_report',
                        locals: {group: group}
                    ) %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/results/_request_data_report.html.erb
<div class="panel-group" id="requests_data">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#requestsData" href="#collapseRequestsData">
          Requests Data
        </a>
      </h4>
    </div>
    <div id="collapseRequestsData" class="panel-collapse collapse in">
      <div class="panel-body">
        <br>
        <table class="table table-hover table-striped table-condensed table-bordered sticky-header" id="requests-results">
          <thead>
          <tr>
            <th></th>
            <th>Mean, msec</th>
            <th>Median, msec</th>
            <th>90% Line, msec</th>
            <th>99% Line, msec</th>
            <th>Min, msec</th>
            <th>Max, msec</th>
            <th>Throughput, req/sec</th>
            <th>Failed requests, %</th>
          </tr>
          </thead>
          <tbody>
          <% @result.calculated_requests_results.where.not(label: 'all_requests').order(:label).each do |calculated_result| %>
              <% requests_histogram_uniq_id = Digest::MD5.bubblebabble(calculated_result.label + '1') %>
              <% requests_percentile_of_values_uniq_id = Digest::MD5.bubblebabble(calculated_result.label + '2') %>
              <tr>
                <td class="labelResult">
                  <% anchor_id = Digest::MD5.bubblebabble(calculated_result.label) %>
                  <%= anchor(anchor_id) %>
                  <div class="bottom10"><%= calculated_result.label %>
                    <%= link_to_anchor_on_report(anchor_id, @result.id) %>
                  </div>
                  <div class="btn-group" role="group">
                    <div class="inline-block">
                      <%= button_to(result_requests_histogram_plot_path(
                                        label: calculated_result.label,
                                        result_id: @result.id,
                                        result_time_cut: @result.time_cutting_percent,
                                        plot_id: requests_histogram_uniq_id
                                    ),
                                    remote: true,
                                    id: "#{requests_histogram_uniq_id}_button",
                                    class: 'btn btn-default btn-xs show-plot requests-histogram-plot-button',
                                    data: { disable_with: 'Loading..' },
                                    'data-toggle' => 'collapse',
                                    'data-target' => "##{requests_histogram_uniq_id}_div") do %>
                          <i class="fa fa-bar-chart"></i>
                      <% end %>
                    </div>
                    <div class="inline-block">
                      <%= button_to(result_percentile_requests_plot_path(
                                        label: calculated_result.label,
                                        result_id: @result.id,
                                        result_time_cut: @result.time_cutting_percent,
                                        plot_id: requests_percentile_of_values_uniq_id
                                    ),
                                    remote: true,
                                    id: "#{requests_percentile_of_values_uniq_id}_button",
                                    class: 'btn btn-default btn-xs show-plot requests-time-plot-button',
                                    data: { disable_with: 'Loading..' },
                                    'data-toggle' => 'collapse',
                                    'data-target' => "##{requests_percentile_of_values_uniq_id}_div") do %>
                          <i class="fa fa-area-chart"></i>
                      <% end %>
                    </div>
                  </div>
                </td>
                <td><%= calculated_result.mean %></td>
                <td><%= calculated_result.median %></td>
                <td><%= calculated_result.ninety_percentile %></td>
                <td><%= calculated_result.ninetynine_percentile %></td>
                <td><%= calculated_result.min %></td>
                <td><%= calculated_result.max %></td>
                <td><%= calculated_result.throughput %></td>
                <td><%= calculated_result.failed_results %></td>
              </tr>
              <tr>
                <td colspan="100" class="hidden-row">
                  <div class="collapse" id="<%= "#{requests_histogram_uniq_id}_div" %>"></div>
                </td>
              </tr>
              <tr>
                <td colspan="100" class="hidden-row">
                  <div class="collapse" id="<%= "#{requests_percentile_of_values_uniq_id}_div" %>"></div>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/results/_requests_chart.html.erb
<% content_for :charts do %>
    <% id = SecureRandom.hex %>
    <div id="<%= id %>"></div>
    <script type='text/javascript'>
        var currentWeb00 = {
            name: 'CURRENT: web00 EXEC ASP.NET\Requests Current',
            x: <%= data[:current][:web00][:x] %>,
            y: <%= data[:current][:web00][:y] %>,
            mode: 'lines',
            line: {
                color: 'red'
            }
        };
        var currentWeb01 = {
            name: 'CURRENT: web11 EXEC ASP.NET\Requests Current',
            x: <%= data[:current][:web01][:x] %>,
            y: <%= data[:current][:web01][:y] %>,
            mode: 'lines',
            line: {
                color: 'green'
            }
        };
        var baseWeb00 = {
            name: 'BASE: web00 EXEC ASP.NET\Requests Current',
            x: <%= data[:base][:web00][:x] %>,
            y: <%= data[:base][:web00][:y] %>,
            mode: 'lines',
            line: {
                color: 'red',
                dash: 'dot',
                width: 2
            }
        };
        var baseWeb01 = {
            name: 'BASE: web11 EXEC ASP.NET\Requests Current',
            x: <%= data[:base][:web01][:x] %>,
            y: <%= data[:base][:web01][:y] %>,
            mode: 'lines',
            line: {
                color: 'green',
                dash: 'dot',
                width: 2
            }
        };
        var layout = {
            title: '<%= name %>',
            xaxis: {
                title: 'Time, s'
            },
            yaxis: {
                title: 'Metrics, %'
            }
        };
        Plotly.newPlot('<%= id %>', [baseWeb00, baseWeb01, currentWeb00, currentWeb01], layout);
    </script>
<% end %>

app/views/results/_results_list.html.erb
<div id="filterrific_results">

  <table id="results-table" class="table table-striped table-bordered">
    <thead>
    <tr>
      <th class="small"></th>
      <th class="small"><%= filterrific_sorting_link(@filterrific, :id) %></th>
      <th class="small"><%= filterrific_sorting_link(@filterrific, :project) %></th>
      <th class="small"><%= filterrific_sorting_link(@filterrific, :version) %></th>
      <th class="small"><%= filterrific_sorting_link(@filterrific, :rps) %></th>
      <th class="small"><%= filterrific_sorting_link(@filterrific, :duration) %></th>
      <th class="small"><%= filterrific_sorting_link(@filterrific, :profile) %></th>
      <th class="small"><%= filterrific_sorting_link(@filterrific, :data_version) %></th>
      <th class="small"><%= filterrific_sorting_link(@filterrific, :test_run_date) %></th>
      <th class="small"><%= filterrific_sorting_link(@filterrific, :time_cutting_percent) %></th>
      <th class="small"><%= filterrific_sorting_link(@filterrific, :smoothing_percent) %></th>
      <th class="small"><%= filterrific_sorting_link(@filterrific, :release_date) %></th>
      <th class="small"><%= filterrific_sorting_link(@filterrific, :comment) %></th>
      <th class="small"></th>
    </tr>
    </thead>

    <tbody>
    <% @results.each do |result| %>
        <tr class="result_row">
          <td class="check-result text-center">
            <%= check_box_tag 'result-checkbox', result.id, @checked_results.try(:include?, result.id.to_s),
                              class: 'result-checkbox' %>
          </td>
          <td class="id nostrech"><%= result.id %></td>
          <td class="project nostrech"><%= result.project.project_name %></td>
          <td class="version"><%= result.version %></td>
          <td class="rps nostrech"><%= result.rps %></td>
          <td class="duration nostrech"><%= result.duration %></td>
          <td class="profile nostrech"><%= result.profile %></td>
          <td class="data_version nostrech"><%= result.data_version %></td>
          <td class="test_run_date nostrech"><%= result.test_run_date %></td>
          <td class="time_cutting_percent nostrech"><%= result.time_cutting_percent %></td>
          <td class="smoothing_percent nostrech"><%= result.smoothing_percent %></td>
          <td class="release_date nostrech"><%= result.release_date.try(:to_date) %></td>
          <td class="comment text-center nostrech"> <%= comment_icon(result.comment) if result.comment.present? %></td>
          <td class="actions nostrech">
            <%= link_to '<i class="glyphicon glyphicon-eye-open"></i>'.html_safe,
                        result_path(result),
                        class: 'showResult' %>
            <%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe,
                        edit_result_path(result),
                        class: 'editResult' %>
            <%= link_to '<i class="glyphicon glyphicon-remove"></i>'.html_safe,
                        result,
                        class: 'destroyResult',
                        method: :delete,
                        data: {confirm: 'Are you sure?'} %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <div id="paginator">
    <%= paginate @results %>
  </div>
</div>

app/views/results/all_requests_histogram_plot.js.erb
$('#all_requests_plot_button').prop('type', 'button');

var result = {
    x: <%= @result_data %>,
    opacity: 0.75,
    name: 'id:<%= params[:result_id] %>',
    type: 'histogram'
};

var layout = {
    title: 'Histogram of response time',
    xaxis: {
        title: 'Response time, ms'
    },
    yaxis: {
        title: 'Number of requests'
    },
    barmode: 'overlay'
};
Plotly.newPlot('all_requests_plot', [result], layout);

app/views/results/compare.html.erb
<div class="container">
  <h1>Compare results</h1>
</div>

app/views/results/index.html.erb
<div class="container">
  <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
  <% end %>

  <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
  <% end %>

  <div class="page-header">
    <h1>Load tests results</h1>
  </div>

  <%= render(partial: 'results/filters') %>

  <div class="row bottom20">
    <div class="pull-right">
      <button id="clear-results" class="btn btn-link" style="display: none;">x</button>
      <span id="result-to-compare-list" class="right10"></span>
      <%= link_to(
              'Compare',
              compare_path(result: @checked_results),
              class: 'btn btn-success btn-lg',
              id: 'compare-button'
          )
      %>
      <%= link_to(
              'Trend',
              trend_path(result: @checked_results),
              class: 'btn btn-success btn-lg',
              id: 'trend-button'
          )
      %>
    </div>
  </div>

  <%= render(
          partial: 'results/results_list',
          locals: {results: @results}
      ) %>
</div>

app/views/results/index.js.erb
<% js = escape_javascript(
  render(partial: 'results/results_list', locals: { results: @results })
) %>
$("#filterrific_results").html("<%= js %>");
handleResultsTable();

app/views/results/toggle.js.erb
$("#compare-button").prop("href", "<%= compare_path(result: @checked_results).html_safe %>");
$("#trend-button").prop("href", "<%= trend_path(result: @checked_results).html_safe %>");
$("#result-to-compare-list").html("<%= escape_javascript(render partial: 'result_to_compare_list', locals: { items: @checked_results} ) %>");