config/routes.rb
Rails.application.routes.draw do
  root 'results#index'

  resources :results do
    member do
      get 'download_requests_data'
      get 'download_performance_data'
      get 'report'
    end
  end

  resources :project

  resources :performance_groups do
    resources :performance_labels
  end

  post 'result/performance_plot' => 'results#performance_plot'
  post 'result/requests_seconds_to_values_plot' => 'results#requests_seconds_to_values_plot'
  post 'result/requests_histogram_plot' => 'results#requests_histogram_plot'
  post 'result/all_requests_histogram_plot' => 'results#all_requests_histogram_plot'
  post 'result/percentile_requests_plot' => 'results#percentile_requests_plot'

  namespace :api do
    resources :results, only: [:create, :index]
    resources :results_with_data_id, only: [:create]
  end

  get 'compare' => 'compare#show'
  namespace 'compare' do
    post 'requests_histogram_plot'
    post 'requests_seconds_to_values_plot'
    post 'all_requests_histogram_plot'
    post 'percentile_requests_plot'
    post 'performance_plot'
  end

  get 'trend' => 'trend#show'
  namespace 'trend' do
    post 'requests_plot'
    post 'performance_plot'
    post 'all_requests_stats_plot'
  end

  get '/request_file/:id', to: 'request_file#show'
  post '/request_file', to: 'request_file#create'

  get '/performance_file/:id', to: 'performance_file#show'
  post '/performance_file', to: 'performance_file#create'

end

app/controllers/compare_controller.rb
class CompareController < ApplicationController
  def show
    flash.keep(:result_ids)
    if params[:result].nil? || params[:result].size == 1
      return redirect_to results_path, alert: 'You should select 2 or more results to compare them'
    end
    result1 = Result.find_by(id: params[:result][0])
    result2 = Result.find_by(id: params[:result][1])
    if result1.nil? || result2.nil?
      return redirect_to results_path, alert: "Can't find selected results"
    end
    flash[:result_ids] = nil # reset choosen results on the result index page

    @compare_report = CompareReport.new(result1, result2)
  end

  def requests_histogram_plot
    @plot_id = params[:plot_id]
    @result1_data = Result.values_of_requests(params[:result1_id], params[:label], params[:result1_time_cut].to_i)
    @result2_data = Result.values_of_requests(params[:result2_id], params[:label], params[:result2_time_cut].to_i)
  end

  def requests_seconds_to_values_plot
    @plot_id = params[:plot_id]
    @result1_data = Result.requests_seconds_to_values(params[:result1_id], params[:label], params[:result1_time_cut].to_i)
    @result2_data = Result.requests_seconds_to_values(params[:result2_id], params[:label], params[:result2_time_cut].to_i)
  end

  def all_requests_histogram_plot
    @result1_data = Result.values_of_requests(params[:result1_id], params[:result1_time_cut].to_i)
    @result2_data = Result.values_of_requests(params[:result2_id], params[:result2_time_cut].to_i)
  end

  def percentile_requests_plot
    @plot_id = params[:plot_id]
    @result1_data = Result.percentile_of_values_of_requests(params[:result1_id], params[:result1_time_cut].to_i, params[:label])
    @result2_data = Result.percentile_of_values_of_requests(params[:result2_id], params[:result2_time_cut].to_i, params[:label])
  end

  def performance_plot
    group = params[:group]
    @unit = group[:units]
    @group_name = group[:name]
    @plot_id = params[:plot_id]
    @result1_data = Result.performance_seconds_to_values(params[:result1_id], group[:labels], params[:result1_time_cut].to_i)
    @result2_data = Result.performance_seconds_to_values(params[:result2_id], group[:labels], params[:result1_time_cut].to_i)
  end
end

app/helpers/compare_helper.rb
module CompareHelper
  def parameter_to_compare?(parameter)
    ['Rps', 'Duration', 'Profile', 'Data version', 'Time cutting percent', 'Value smoothing interval'].include? parameter
  end

  def link_to_result(result_id, prefix = nil)
    link_to "#{prefix}#{result_id}", result_path(result_id)
  end
end

app/views/compare/_description_compare_report.html.erb
<div class="panel-group" id="description">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#description" href="#collapseDescription">
          Description
        </a>
      </h4>
    </div>
    <div id="collapseDescription" class="panel-collapse collapse in">
      <div class="panel-body">
        <div class="col-md-6">
          <table class="table table-striped table-condensed table-responsive table-bordered">
            <h4>Test run parameters</h4>
            <thead>
              <tr>
                <th>Parameter</th>
                <th>Result id:<%= @compare_report.result1.id %></th>
                <th>Result id:<%= @compare_report.result2.id %></th>
              </tr>
            </thead>
            <tbody>
              <% @compare_report.description.each do |parameter, value| %>
                <tr class="<%= 'row-warning' if parameter_to_compare?(parameter) && value[:result1].to_s != value[:result2].to_s %>">
                  <td><%= parameter %></td>
                  <td><%= value[:result1] %></td>
                  <td><%= value[:result2] %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/compare/_performance_data_compare_report.html.erb
<div class="panel-group" id="perfmon_data">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#perfmon_data" href="#collapsePerfmonData">
          Performance results
        </a>
      </h4>
    </div>
    <div id="collapsePerfmonData" class="panel-collapse collapse in">
      <div class="panel-body">
        <% @compare_report.performance_groups.each do |group| %>
            <% case %>
        <% when group[:metrics_type] == PerformanceGroup.define_metrics_type[:dynamic], group[:metrics_type] == nil %>
                <%= render(
                        partial: 'compare/performance_dynamic_metrics_compare_report',
                        locals: {group: group}
                    ) %>
            <% when group[:metrics_type] == PerformanceGroup.define_metrics_type[:static] %>
                <%= render(
                        partial: 'compare/performance_static_metrics_compare_report',
                        locals: {group: group}
                    ) %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/compare/_performance_dynamic_metrics_compare_report.html.erb
<h4 style="color: #2a6496"><%= group[:name] %></h4>
<table class="table table-hover table-striped table-condensed table-responsive table-bordered">
  <thead>
  <tr>
    <th></th>
    <th>Mean id:<%= @compare_report.result1.id %></th>
    <th>Mean id:<%= @compare_report.result2.id %></th>
    <th>Mean trend, %</th>
    <th>Min id:<%= @compare_report.result1.id %></th>
    <th>Min id:<%= @compare_report.result2.id %></th>
    <th>Max id:<%= @compare_report.result1.id %></th>
    <th>Max id:<%= @compare_report.result2.id %></th>
  </tr>
  </thead>
  <tbody>
  <% group[:labels].each do |label| %>
      <tr>
        <td>
          <% anchor_id = Digest::MD5.bubblebabble(label) %>
          <%= anchor(anchor_id) %>
          <%= label %>
          <%= link_to_anchor_on_compare(anchor_id, [@compare_report.result1.id, @compare_report.result2.id]) %>
        </td>
        <td><%= @compare_report.result1.calculated_performance_results.find_by(label: label).mean %></td>
        <td><%= @compare_report.result2.calculated_performance_results.find_by(label: label).mean %></td>
        <td class="mean trend"><%= @compare_report.trend(:calculated_performance_results, :mean, label, group[:trend_limit]) %></td>
        <td><%= @compare_report.result1.calculated_performance_results.find_by(label: label).min %></td>
        <td><%= @compare_report.result2.calculated_performance_results.find_by(label: label).min %></td>
        <td><%= @compare_report.result1.calculated_performance_results.find_by(label: label).max %></td>
        <td><%= @compare_report.result2.calculated_performance_results.find_by(label: label).max %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<% label_uniq_id = Digest::MD5.bubblebabble(group[:name]) %>
<%= button_to 'Show a plot',
              compare_performance_plot_path(
                  group: group,
                  result1_id: @compare_report.result1.id,
                  result2_id: @compare_report.result2.id,
                  result1_time_cut: @compare_report.result1.time_cutting_percent,
                  result2_time_cut: @compare_report.result2.time_cutting_percent,
                  version1: @compare_report.result1.version,
                  version2: @compare_report.result2.version,
                  test_run_date1: @compare_report.result1.test_run_date.strftime('%d.%m.%Y %H:%M'),
                  test_run_date2: @compare_report.result2.test_run_date.strftime('%d.%m.%Y %H:%M'),
                  plot_id: label_uniq_id
              ),
              remote: true,
              id: "#{label_uniq_id}_button",
              class: 'btn btn-default show-plot bottom20',
              data: {disable_with: 'Loading..'},
              'data-toggle' => 'collapse',
              'data-target' => "##{label_uniq_id}_div" %>
<div class="collapse" id="<%= "#{label_uniq_id}_div" %>"></div>

app/views/compare/_performance_static_metrics_compare_report.html.erb
<h4 style="color: #2a6496"><%= group[:name] %></h4>
<table class="table table-hover table-striped table-condensed table-responsive table-bordered table-nonfluid">
  <thead>
  <tr>
    <th></th>
    <th>Last value id:<%= @compare_report.result1.id %></th>
    <th>Last value id:<%= @compare_report.result2.id %></th>
    <th>Last value trend, %</th>
  </tr>
  </thead>
  <tbody>
  <% group[:labels].each do |label| %>
      <tr>
        <td>
          <% anchor_id = Digest::MD5.bubblebabble(label) %>
          <%= anchor(anchor_id) %>
          <%= label %>
          <%= link_to_anchor_on_compare(anchor_id, [@compare_report.result1.id, @compare_report.result2.id]) %>
        </td>
        <td><%= @compare_report.result1.calculated_performance_results.find_by(label: label).last_value %></td>
        <td><%= @compare_report.result2.calculated_performance_results.find_by(label: label).last_value %></td>
        <td class="mean trend"><%= @compare_report.trend(:calculated_performance_results, :last_value, label, group[:trend_limit]) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/compare/_requests_plots.html.erb
<% all_requests_percentile_of_values_uniq_id = Digest::MD5.bubblebabble('all' + '2') %>

<%= button_to 'Response time distribution',
    compare_all_requests_histogram_plot_path(
      result1_id: @compare_report.result1.id,
      result2_id: @compare_report.result2.id,
      version1: @compare_report.result1.version,
      version2: @compare_report.result2.version,
      test_run_date1: @compare_report.result1.test_run_date.strftime('%d.%m.%Y %H:%M'),
      test_run_date2: @compare_report.result2.test_run_date.strftime('%d.%m.%Y %H:%M'),
      result1_time_cut: @compare_report.result1.time_cutting_percent,
      result2_time_cut: @compare_report.result2.time_cutting_percent
    ),
    remote: true,
    id: 'all_requests_plot_button',
    class: 'btn btn-default show-plot bottom20',
    data: { disable_with: 'Loading..' },
    'data-toggle' => 'collapse',
    'data-target' => '#all_requests_plot' %>

<div class="collapse" id="all_requests_plot"></div>
<%= button_to 'Percentile of requests',
    compare_percentile_requests_plot_path(
      result1_id: @compare_report.result1.id,
      result2_id: @compare_report.result2.id,
      version1: @compare_report.result1.version,
      version2: @compare_report.result2.version,
      test_run_date1: @compare_report.result1.test_run_date.strftime('%d.%m.%Y %H:%M'),
      test_run_date2: @compare_report.result2.test_run_date.strftime('%d.%m.%Y %H:%M'),
      result1_time_cut: @compare_report.result1.time_cutting_percent,
      result2_time_cut: @compare_report.result2.time_cutting_percent,
      plot_id: all_requests_percentile_of_values_uniq_id
    ),
    remote: true,
    id: "#{all_requests_percentile_of_values_uniq_id}_button",
    class: 'btn btn-default show-plot bottom20',
    data: { disable_with: 'Loading..' },
    'data-toggle' => 'collapse',
    'data-target' => "##{all_requests_percentile_of_values_uniq_id}_div" %>

<div class="collapse" id="<%= "#{all_requests_percentile_of_values_uniq_id}_div" %>"></div>

app/views/compare/all_requests_histogram_plot.js.erb
$('#all_requests_plot_button').prop('type', 'button');

var result1 = {
  x: <%= @result1_data %>,
  opacity: 0.75,
  name: '<%= params[:version1]%> (<%= params[:test_run_date1]%>)',
  type: 'histogram'
};
var result2 = {
  x: <%= @result2_data %>,
  opacity: 0.75,
  name: '<%= params[:version2]%> (<%= params[:test_run_date2]%>)',
  type: 'histogram'
};
var layout = {
  title: 'Histogram of response time',
  xaxis: {
    title: 'Response time, ms'
  },
  yaxis: {
    title: 'Number of requests'
  },
  legend: {
    orientation: 'h',
    x: 0.3,
    y: -0.3
  },
  barmode: 'overlay'
};
Plotly.newPlot('all_requests_plot', [result1, result2], layout);

app/views/compare/histogram_requests_plot.js.erb
$('#<%= "#{@div_id}_button" %>').prop('type', 'button');

var result1 = {
    x: <%= @result1_data %>,
    opacity: 0.75,
    name: 'First',
    type: 'histogram'
};
var result2 = {
    x: <%= @result2_data %>,
    opacity: 0.75,
    name: 'Second',
    type: 'histogram'
};
var layout = {
    title: 'Histogram of response time',
    xaxis: {
        title: 'Response time, ms'
    },
    yaxis: {
        title: 'Number of requests'
    },
    barmode: 'overlay'
};
Plotly.newPlot('<%= @div_id %>', [result1, result2], layout);

app/views/compare/percentile_requests_plot.js.erb
$('#<%= "#{@plot_id}_button" %>').prop('type', 'button');


var result1 = {
    x: <%= @result1_data[:values] %>,
    y: <%= @result1_data[:percentiles] %>,
    name: '<%= params[:version1]%> (<%= params[:test_run_date1]%>)',
    mode: 'lines',
    line: {shape: 'spline'},
    type: 'scatter'
};

var result2 = {
    x: <%= @result2_data[:values] %>,
    y: <%= @result2_data[:percentiles] %>,
    name: '<%= params[:version2]%> (<%= params[:test_run_date2]%>)',
    mode: 'lines',
    line: {shape: 'spline'},
    type: 'scatter'
};
var layout = {
    title: 'Response time percentiles',
    xaxis: {
        title: 'Response time, ms'
    },
    yaxis: {
        title: 'Percentile'
    },
    legend: {
        orientation: 'h',
        x: 0.3,
        y: -0.3
    }
};
Plotly.newPlot('<%= "#{@plot_id}_div" %>', [result1, result2], layout);

app/views/compare/performance_plot.js.erb
$('#<%= "#{@plot_id}_button" %>').prop('type', 'button');

var colors = ['blue', 'green', 'red', 'gray', 'orange', 'brown', 'purple', 'olive'];
var colors_dup = colors.slice();

var lines_first = [];
<% @result1_data.each do |label, data| %>
  var label_plot = {
    x: <%= data[:seconds] %>,
    y: <%= data[:values] %>,
    name: '<%= "#{label} - #{ params[:version1]} (#{params[:test_run_date1]})"%>',
    mode: 'lines',
    line: {
      dash: 'dot',
      color: colors.shift()
    }
  };
  lines_first.push(label_plot);
<% end %>

var lines_second = [];
<% @result2_data.each do |label, data| %>
  var label_plot = {
    x: <%= data[:seconds] %>,
    y: <%= data[:values] %>,
    name: '<%= "#{label} - #{ params[:version2]} (#{params[:test_run_date2]})"%>',
    mode: 'lines',
    line: {
      color: colors_dup.shift()
    }
  };
  lines_second.push(label_plot);
<% end %>

var layout = {
  title: '<%= @group_name %>',
  xaxis: {
      title: 'Time, seconds'
  },
  yaxis: {
      title: 'Metrics, <%= @unit %>'
  },
  legend: {
    orientation: 'v',
    x: 0.3,
    y: -0.8
  }
};
Plotly.newPlot('<%= "#{@plot_id}_div" %>', lines_first.concat(lines_second), layout);

app/views/compare/requests_histogram_plot.js.erb
$('#<%= "#{@plot_id}_button" %>').prop('type', 'button');

var result1 = {
  x: <%= @result1_data %>,
  opacity: 0.75,
  name: '<%= params[:version1]%> (<%= params[:test_run_date1]%>)',
  type: 'histogram'
};
var result2 = {
  x: <%= @result2_data %>,
  opacity: 0.75,
  name: '<%= params[:version2]%> (<%= params[:test_run_date2]%>)',
  type: 'histogram'
};
var layout = {
  title: 'Response time distribution',
  xaxis: {
    title: 'Response time, ms'
  },
  yaxis: {
    title: 'Number of requests'
  },
  legend: {
    orientation: 'h',
    x: 0.3,
    y: -0.3
  },
  barmode: 'overlay'
};
Plotly.newPlot('<%= "#{@plot_id}_div" %>', [result1, result2], layout);

app/views/compare/requests_seconds_to_values_plot.js.erb
$('#<%= "#{@plot_id}_button" %>').prop('type', 'button');

var result1 = {
  x: <%= @result1_data[:seconds] %>,
  y: <%= @result1_data[:values] %>,
  opacity: 0.75,
  name: '<%= params[:version1]%> (<%= params[:test_run_date1]%>)',
  mode: 'lines'
};
var result2 = {
  x: <%= @result2_data[:seconds] %>,
  y: <%= @result2_data[:values] %>,
  opacity: 0.75,
  name: '<%= params[:version2]%> (<%= params[:test_run_date2]%>)',
  mode: 'lines'
};
var layout = {
  title: 'Response time to seconds',
  xaxis: {
    title: 'Time, seconds'
  },
  yaxis: {
    title: 'Response time, ms'
  },
  legend: {
    orientation: 'h',
    x: 0.3,
    y: -0.3
  }
};
Plotly.newPlot('<%= "#{@plot_id}_div" %>', [result1, result2], layout);

app/views/compare/show.html.erb
<div class="container-fluid">
  <div class="page-header">
    <h1>Compare report <small>(<%= link_to_result(@compare_report.result1.id, 'id:') %> vs
      <%= link_to_result(@compare_report.result2.id, 'id:') %>)
      <%= link_to compare_path(result: [@compare_report.result2.id, @compare_report.result1.id]), {:id => 'changed_results'} do %>
          <i class="fa fa-exchange"></i>
      <% end %></small>
    </h1>
  </div>

  <% if @compare_report.differences.present? %>
    <div class="row">
      <div id="different-warning" class="alert alert-warning" role="alert">
        <strong>Warning!</strong>
        <ul>
          <% @compare_report.differences.each do |warning| %>
            <li><%= warning %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <%= render 'compare/description_compare_report' %>
  </div>

  <div class="row">
    <%= render 'compare/requests_plots' %>
  </div>

  <% if @compare_report.performance? %>
      <div class="row">
        <%= render 'compare/performance_data_compare_report' %>
      </div>
  <% end %>

  <div class="row">
    <%= render 'compare/request_data_compare_report' %>
  </div>
</div>