config/routes.rb
Rails.application.routes.draw do
  root 'results#index'

  resources :results do
    member do
      get 'download_requests_data'
      get 'download_performance_data'
      get 'report'
    end
  end

  resources :project

  resources :performance_groups do
    resources :performance_labels
  end

  post 'result/performance_plot' => 'results#performance_plot'
  post 'result/requests_seconds_to_values_plot' => 'results#requests_seconds_to_values_plot'
  post 'result/requests_histogram_plot' => 'results#requests_histogram_plot'
  post 'result/all_requests_histogram_plot' => 'results#all_requests_histogram_plot'
  post 'result/percentile_requests_plot' => 'results#percentile_requests_plot'

  namespace :api do
    resources :results, only: [:create, :index]
    resources :results_with_data_id, only: [:create]
  end

  get 'compare' => 'compare#show'
  namespace 'compare' do
    post 'requests_histogram_plot'
    post 'requests_seconds_to_values_plot'
    post 'all_requests_histogram_plot'
    post 'percentile_requests_plot'
    post 'performance_plot'
  end

  get 'trend' => 'trend#show'
  namespace 'trend' do
    post 'requests_plot'
    post 'performance_plot'
    post 'all_requests_stats_plot'
  end

  get '/request_file/:id', to: 'request_file#show'
  post '/request_file', to: 'request_file#create'

  get '/performance_file/:id', to: 'performance_file#show'
  post '/performance_file', to: 'performance_file#create'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">LoadResult</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'results' && action_name == "index"%>"><a href="/results">Results</a></li>
      </ul>
      <!-- only direct link
      <ul class="nav navbar-nav navbar-left">
        <li class="<%= 'active' if params[:controller] == 'project' && action_name == "index" %>">
          <%= link_to 'Projects', project_index_path %>
        </li>
      </ul>
      -->
      <ul class="nav navbar-nav navbar-left">
        <li class="<%= 'active' if (params[:controller] == 'performance_groups'||params[:controller] == 'performance_labels') && action_name == "index" %>">
          <%= link_to 'Performance groups and labels', performance_groups_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if action_name == "new"%>">
          <%= link_to 'Upload results', new_result_path %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoadResult</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render('layouts/navbar') %>
<%= yield %>
</body>
</html>